package config

import "dynamic_template_rendering/models"

var TileConfigs = []models.TileConfig{
	{
		Keyword:      "USA",
		PT:           "5-7",
		Amenities:    "",
		TilesPerPage: 4,
		TotalTiles:   8,
		Order:        "1",
		Mode:         map[string]interface{}{},
		TilesBlockID: "ile57am",
		Layout:       "row",
		Properties:   []interface{}{},
	},
	{
		Keyword:      "USA",
		PT:           "3-4-10",
		Amenities:    "",
		TilesPerPage: 4,
		TotalTiles:   8,
		Order:        "4",
		Mode:         map[string]interface{}{},
		TilesBlockID: "ipv1476",
		Layout:       "row",
		Properties:   []interface{}{},
	},
	{
		Keyword:      "USA",
		PT:           "5-7-6-12",
		Amenities:    "",
		TilesPerPage: 4,
		TotalTiles:   8,
		Order:        "3",
		Mode:         map[string]interface{}{},
		TilesBlockID: "i79etyf",
		Layout:       "row",
		Properties:   []interface{}{},
	},
	{
		Keyword:      "USA",
		PT:           "4-10-1-11-5-7",
		Amenities:    "",
		TilesPerPage: 4,
		TotalTiles:   8,
		Order:        "1",
		Mode:         map[string]interface{}{},
		TilesBlockID: "iga91sh",
		Layout:       "row",
		Properties:   []interface{}{},
	},
	{
		Keyword:      "USA",
		PT:           "3-4-10-13-16-7-5-11-2-14",
		Amenities:    "",
		TilesPerPage: 4,
		TotalTiles:   8,
		Order:        "3",
		Mode:         map[string]interface{}{},
		TilesBlockID: "i0fx4v9",
		Layout:       "row",
		Properties:   []interface{}{},
	},
	{
		Keyword:      "USA",
		PT:           "",
		Amenities:    "",
		TilesPerPage: 4,
		TotalTiles:   8,
		Order:        "1",
		Mode:         map[string]interface{}{},
		TilesBlockID: "i27435y",
		Layout:       "row",
		Properties:   []interface{}{},
	},
	{
		Keyword:      "USA",
		PT:           "3-4-10",
		Amenities:    "",
		TilesPerPage: 4,
		TotalTiles:   8,
		Order:        "3",
		Mode:         map[string]interface{}{},
		TilesBlockID: "i5w70hj",
		Layout:       "row",
		Properties:   []interface{}{},
	},
}